# Generated by Django 5.0.6 on 2024-05-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='github_profile',
        ),
    ]
