# Generated by Django 5.0.6 on 2024-05-28 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_alter_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
