# Generated by Django 5.0.6 on 2024-05-24 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_rename_discrption_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='discrption',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
