# Generated by Django 5.0.6 on 2024-05-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_details',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_details',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_Details',
        ),
    ]
