# Generated by Django 5.0.6 on 2024-05-31 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_remove_order_details_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='url',
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_images'),
        ),
    ]
