# Generated by Django 5.0.6 on 2024-05-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_alter_productimages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='url',
        ),
    ]
